### ISSUE TITLE
[ENHANCEMENT] Any way  to export the list and import it later in the tool so i could generate a new report later?

### ISSUE THREAD

**Issue by kiriasCMNH** [ghostinthewires/Azure-Readiness-Checklist#22]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]
is there any way  to export the list and import it later in the tool so i could generate a new report later?
**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.
Maybe having the ability to export a json containing all the categories and structure we want for our report so we can import it later at the web tool for generating a report later, we want to have some form of source control of the structures of each report for different apps..
**Describe alternatives you've considered**
I tried using the download button but that only kind of downloaded a json with the filter options.
**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version the docs.
Maybe a screenshot or design?

**Comment by ghostinthewires** [comment]
Hi,

This is already available with the download / upload buttons:

![image](https://user-images.githubusercontent.com/15887450/139907943-7029d444-4685-4b40-a4cb-adfbc58fb330.png)

**Comment by kiriasCMNH** [comment]
Ok thanks for clarifying, i think i misunderstood how the list worked, so each category and its items are fixed as well right? so we cannot create our own?

**Comment by ghostinthewires** [comment]
Yeah, they are as you see, fixed. So you cant create your own from it
